# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad270391055b22faabfa9ac894f73e4a3bf732c198193b5e3a08c248ddf7a84bf8bb5391a8bddc2c7f224e8e9e2e66e907f76f520bac844a57e6402e246757e

test:
  secret_key_base: b6baff5fed3da0f2a1fb356bc0326aeb33fac3486ab10df76e1cea45bc9cf28dadfac7d013a3e9b8b79cff5baf64c7228f22ec7cbc557f5394490f0e8a46a1cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
